### ISSUE TITLE
Context and Results for JuliaCon Proceedings

### ISSUE THREAD

**Issue by christianpeel** [IBM/TSML.jl#90]
In the paper you give several examples of the use of TSML, but I didn't catch what we should be comparing TSML against.  Specifically, you have results that compare different tools that can be accessed from within TSML, but no results from some other Julia or non-Julia packages to show that TSML is better or worse in any way.  It's certainly possible that I missed it; could you help me out? 

I.e. I'm looking at the "Context" and "Results" items in the JuliaCon [Proceedings issue](https://github.com/JuliaCon/proceedings-review/issues/51).

**Comment by ppalmes** [comment]
Hi @christianpeel,

In the latest pdf: 

https://github.com/JuliaCon/proceedings-papers/blob/jcon.00051/jcon.00051/10.21105.jcon.00051.pdf

Section 5 compares the different MLs from R, Julia, and ScikitLearn. TSML uses a wrapper for R caret and Python ScikitLearn so that they can easily be used without much difference in julia syntax by calling the fit! and transform! multidispatch functions. The comparison is more of showing the feasibility of combining different MLs from different libraries.

**Comment by christianpeel** [comment]
I apologize for my confusion.   To be clear, is there a package like TSML.jl in R or Python or Swift that has similar functionality that you might compare against? 

My understanding is that Section 5 of your paper compares the performance of specific tools on specific models; to be clear, this is useful. I may have missed it, but I do not recall seeing a comparison of TSML.jl with any similar packages.   If indeed there is some other packages comparable to TSML.jl in Julia or R or Python or some other language, then I'd like to know how TSML.jl compares against them. If TSML.jl is unique, then that is useful info and could go in your paper.

**Comment by ppalmes** [comment]
TSML.jl is like scikitlearn in python and caret in R. all of them create a common wrapper for MLs in their respective languages. what is unique with TSML is that it has a wrapper to use the MLs in both caret and scikitlearn. In the comparison, you have performance of MLs from R thru caret and scikitlearn from Python against ensembles written in Julia. the advantage of TSML is that you can run libraries from R and python and combine them for complex ensembles. so far, i have not seen a metapackage that combines all MLs written in R, Python, and Julia working together seamlessly. Since each ML library in R are compiled, calling them from R and from Julia thru RCall are not much different. The comparisons can be considered among different MLs.

**Comment by ppalmes** [comment]
For example, these are the possible ML models in R which can be called using the caret common wrapper function of train and predict: https://topepo.github.io/caret/available-models.html

Although I have not exhaustively test all MLs in R, TSML also can call them using the fit! and transform! multi-dispatch functions of TSML using RCall package as the middleware between Julia and R communication.

**Comment by christianpeel** [comment]
Perhaps it would pay to look at other metapackages like JuMP.jl, Plots.jl, DifferentialEquations.jl to see what words they use to describe themselves.

**Comment by ppalmes** [comment]
The ultimate goal of the ML part in TSML is to automatically pick the right ensemble architecture where the elements are coming from the different ML libraries. The challenge is to have a metaML optimize both the parameters and architecture of  the bunch of MLs for a given problem. This is similar to autoML but the focus is more on automatic meta modeling instead entire pipeline which the autoML targets. This is in contrast to the Plots.jl or DifferentialEquations.jl which does not involve automatic modeling and learning.

**Comment by christianpeel** [comment]
I mentioned JuMP.jl, Plots.jl, and DifferentialEquations.jl because they are metapackages. I did not intend any direct comparison of the functionality of the packages with TSML.jl. I only mentioned them as a possible place to look for words that describe a metapackage; i.e. words other than "package".

**Comment by ppalmes** [comment]
yes, i know what you mean. i think ensemble is more appropriate than meta-package because the combination is data-driven and dynamic. thanks for the suggestions. i’ll try to improve the explanation. the idea is an evolution of different versions. i just started with mostly filters and now extending it to ensemble learning.
